

-- i has update tables maybe you get an error
   
--ALTER session set NLS_DATE_FORMAT='yyyy-MM-dd';
 
  
--ALTER session set NLS_DATE_FORMAT='DD-MM-YYYY'; 


 
    
 
create table person(
    person_in number(10) not null,
    Fname varchar2(50),
    Mname varchar2(50),
    Lname varchar2(50),
    phone number(10),
    gender char,
    addres varchar2(200),
    birth_date date,
     email varchar2(100),
    password varchar2(50),
    CONSTRAINT person_pk PRIMARY KEY (person_in)
);

create table manager(
    manager_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    person_in number(10),
    start_date date,
    salary number(10),
    CONSTRAINT manager_pk primary key(manager_id),
    CONSTRAINT person_fk FOREIGN KEY (person_in) REFERENCES person(person_in) ON DELETE CASCADE
);

create table super(
    super_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    manager number(10),
    CONSTRAINT super_pk PRIMARY KEY (super_id),
    CONSTRAINT manager_fk FOREIGN KEY (manager) REFERENCES manager(manager_id) ON DELETE CASCADE
);



create table customer(
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    person number(10),
    days int,
    CONSTRAINT customer_pk primary key(customer_id),
    CONSTRAINT customer_person_fk FOREIGN KEY (person) REFERENCES person(person_in)
);

create table car(
    plate varchar2(20),
    day_price int,
    name varchar2(30),
    color varchar2(20),
    year varchar2(4),
    model varchar2(100),
    sunfoor number(1),
    engine varchar2(100),
    transmission varchar2(30),
    image_path BFILE,
    constraint car_pk primary key(plate)
);


create table rental(
    rental_id number generated by default as IDENTITY,
    customer number(10),
    manager number(10),
    car varchar2(20),
    start_date date,
    end_date date,
    constraint rental_pk primary key (rental_id),
    constraint rental_customer_fk foreign key(customer) references customer(customer_id) ON DELETE CASCADE,
    constraint rental_manager_fk foreign key(manager) references manager(manager_id) ON DELETE CASCADE,
    constraint rental_car_fk foreign key(car) references car(plate) ON DELETE CASCADE
);

create table payment(
    payment_id number generated by default as identity,
    rental number,
    amount int,
    creted_date date,
    constraint payment_pk primary key (payment_id),
    constraint payment_rental_fk foreign key (rental) references rental(rental_id)
);

create table discount(
    payment number,
    amount float,
    discount_id number generated by default as identity,
    constraint discount_pk primary key(discount_id),
    constraint discount_payment_fk foreign key(payment) references payment(payment_id)
);

create table customerDiscount(
    id number generated by default as IDENTITY,
    OnlineDiscount number(4),
    discount number(4)
);



